_target_: boltzgen.task.filter.filter.Filter
budget: 50
top_budget: 10
use_affinity: false
use_ipsae: true
filter_cysteine: true
from_inverse_folded: true
filter_designfolding: false
filter_bindingsite: false
modality: antibody
peptide_type: linear
alpha: 0.001
random_state: 0
metrics_override: null
num_liability_plots: 0
plot_seq_logos: false
dual_output: true
additional_filters:
- feature: design_to_target_iptm
  lower_is_better: false
  threshold: 0.8
- feature: design_ptm
  lower_is_better: false
  threshold: 0.75
design_dir: nipah_vhh_output/intermediate_designs_inverse_folded
outdir: nipah_vhh_output
filter_biased: true
